name: Build and deploy Angular

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.19
          cache: "npm"
          cache-dependency-path: ./package-lock.json

      - name: Install dependencies
        working-directory: ./
        run: npm install

      - name: Update config.json for production
        run: |
          cat << 'EOF' > public/assets/config.json
          {
            "apiUrl": "https://secureapi.jennerorozcoa.dev/v1",            
            "recaptchaSiteKey": "6LdC_R4sAAAAALdkIRCXk4rtgo42XPwgRSEd7A2w",
            "googleClientId": "966637622172-7pu5ak4ujjif94pphjum28uppir4ursn.apps.googleusercontent.com",
            "appUuid": "373166e7-5491-11f1-9e08-b904e36964b7",
            "vapidPublicKey": "BAWTud9m5pdyEThXL_cJ1zAh26jB-OMBbQ-Yin0VUfqsHTCkxVMLGI1xqp5W7blvRPLy24t300RaLHTTzGBTRUY",
            "notificationApiUrl": "https://notificationapi.jennerorozcoa.dev/v1",
            "financeApiUrl": "https://financial.jennerorozcoa.dev/v1/finance",
            "crmApiUrl": "https://crm.jennerorozcoa.dev/v1/crm",
            "reportApiUrl": "https://reportapi.jennerorozcoa.dev/v1/report"
          }
          EOF

      - name: Build Angular app
        working-directory: ./
        run: npm run build -- --configuration production

      - name: Deploy to deploy branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/securex-app/browser
          publish_branch: deploy
          force_orphan: true
